language: node_js
node_js:
  - "12"
sudo: required
dist: trusty
addons:
  chrome: stable
  artifacts:
    debug: false
    paths:
      - theSrc/test/snapshots/travis
before_install:
  - sudo apt-get update
script:
  - export ENV="travis"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - google-chrome-stable --version
  - npm run travisTest
